### ISSUE TITLE
 how to create or edit level

### ISSUE THREAD

**Issue by felpcereti** [PizzaJJJ/cursors-server#1]

**Comment by felpcereti** [comment]
pls answer

**Comment by PizzaJJJ** [comment]
Sorry for a really long response. Level creation is a bit complicated now, there are two ways:

**Way 1**
1. Go to [http://cursors.io/?=editor](url).
2. Compose your level.
3. Open the console and call `generateCode()`.
4. Process the above command's output with Level Parser: [https://github.com/PizzaJJJ/cursors-level-parser](url), resulting with a valid JSON level code for the server.

**Way 2**
1. Use more user-friendly level editor: [https://github.com/PizzaJJJ/cursors-level-editor](url).
2. Compose your level.
3. Obtain the level code via 'show level code' or 'save as .txt file' buttons.
4. Process the obtained code with Level Parser: [https://github.com/PizzaJJJ/cursors-level-parser](url), resulting with a valid JSON level code for the server.
