### ISSUE TITLE
when connecting to it using client it crashing 

### ISSUE THREAD

**Issue by mathmakgakpak** [PizzaJJJ/cursors-server#3]
when using cheat it crashing too

**Comment by mathmakgakpak** [comment]
![image](https://user-images.githubusercontent.com/44949126/60512698-94cde780-9cd5-11e9-95db-4c2afbf5b397.png)

**Comment by bensimms1** [comment]
You have to delete bufferreader and bufferwriter then go to cursors io server master which is in the readme.md which is what its based on. copy bufferreader and budferwriter to the same folder. Then it should work
